version: '3'
services:
  app:
    build: .
    container_name: vite-app
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Prevents overwriting node_modules
    command: npm run dev -- --host
